// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lavqjajigdprookmxzsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhdnFqYWppZ2Rwcm9va214enNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5NTE5MDksImV4cCI6MjA0OTUyNzkwOX0.ELlelh7WrRNZCExHDyVgL-kZDfvLtzI_poiZVfMYfLg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);